### ISSUE TITLE
Crashing when opening

### ISSUE THREAD

**Issue by docwin** [travislang/gspro-garmin-connect-v2#10]
I am having issues with the app crashing after opening as admin (~1 seconds after opening). I've tried deleting and reinstalling 3 times. I also tried version 1.3.1 but that one doesn't work either.

To put into context, I am using a Macbook Pro with Parallel (allowed for apps to be "opened from anywhere"), GS Pro latest update, Parallel Pro, Macbook Pro M1 Pro 10/16/16 core chip, MacOS 13.0.1.

I know a native Windows would be best, but I'm trying to avoid buying a separate computer for the simulator. TIA!

https://user-images.githubusercontent.com/121844993/210301986-82314954-4760-43e4-b17b-509ed182a68a.mov

**Comment by docwin** [comment]
For those who are using Mac and Parallels, I got it to work -- you need to copy the folder to the C-drive in the Parallels virtual machine. The exe file should work at that point.

Additionally, your Garmin app will have trouble connecting to your IP address -- you need to create a Bridged Ethernet Network via configure on the virtual machine-->hardware-->network adaptor-->bridged ethernet-->default adaptor.  This should change your IPv4 address from 10.211.x.x to 192.xxx.x.x. If you use the 10.211.x.x, it will say to turn on the E6/Garmin/etc. and won't connect. Once you see the 192.xxx.x.x IP address, it should connect just fine.

**Comment by Drmic2015** [comment]
thank you guys soooo much! been racking my brain at this for an hour now!
