### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by rmhays25** [travislang/gspro-garmin-connect-v2#11]
Hi All,
I had GSPro working with my R10 for months in the middle of last year, but now that the weather has turned and I'm ready for sim golf again, I can't get it to connect and I don't know what changed. After selecting E6 and entering Port and Host info, I repeatedly get "Connection Error: Please make sure your E6 Connect Software is running, and check your computer name and port number before trying again". I have confirmed cell phone and laptop are on the same wifi, I allowed GSPLauncher and gspro-r10-connect through the firewall, and when that didn't work I attempted with the firewall turned off and have had no luck. Everything is being run as admin, and there are no other IP addresses in the wrench icon. Any help is appreciated!

**Comment by travislang** [comment]
What version are you using?

**Comment by rmhays25** [comment]
Spent some time with Garmin support and it was resolved on their end. Thank you for the response and I'm so sorry to bother you with it. Thanks for all you do!
