### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by alwayscur1ous** [travislang/gspro-garmin-connect-v2#2]
![unknown](https://user-images.githubusercontent.com/108561044/179324662-c3aa5e7d-ce58-4c19-92a6-171294754e3a.png)

**Comment by rlefig** [comment]
Hi I get the same error as well frequently. Not sure why but I have to restart the connector

**Comment by WaylonBrown** [comment]
Same here.

**Comment by Kieffer87** [comment]
Also keep running into this.

**Comment by travislang** [comment]
I am planning on releasing an update that will fix this in the next couple weeks

**Comment by JLag1** [comment]
@travislang Any update on this fix yet mate?

**Comment by travislang** [comment]
@JLag1 working on it now

**Comment by travislang** [comment]
This is fixed with this update #9

**Comment by JLag1** [comment]
@travislang you're the man! Thanks for all the effort you put in.
