### ISSUE TITLE
GSPro v2 - Angle of attack and other metrics

### ISSUE THREAD

**Issue by alvingee3019** [travislang/gspro-garmin-connect-v2#4]
Hello, this connector is brilliant and have been able to successfully pair my Garmin R10 with the GS Pro (v1 and v2). The newly release V2 supports additional metrics like Angle of Attack, Club Path, and other metrics supported by Garmin R10 but it doesn't seem to be reading these metrics. Is it possible for this connect package to send those metrics to GS Pro?

**Comment by Datapipes** [comment]
You can replace the env.js and garminconnet.js files with the one provided in the src folder. It will add club data to GSPro

**Comment by joshuawlambert** [comment]
Same issue. @Datapipes not sure what you mean by replacing the env.js and garminconnect.js files. @travislang is there a possible update incoming? Thanks for this great tool!

**Comment by JustMike70** [comment]
Another vote for Angle of Attack being passed to GSPro. Not sure I understand the replacing of .js files if I'm honest!

**Comment by jagalexander** [comment]
yes, i vote for adding AoA as well, would be very useful to get this metric.

**Comment by jfischer209** [comment]
Also voting for Angle of Attack

**Comment by jfischer209** [comment]
> You can replace the env.js and garminconnet.js files with the one provided in the src folder. It will add club data to GSPro

This doesn't look like a valid solution. I moved the files in and still no AoA in GSPro from the R10.

**Comment by jfischer209** [comment]
Ok, did a little more investigation. Using WireShark to capture the packets sent from the Garmin app on the iphone to the PC with the Garmin Connect software and GsPro I could see exactly which data fields are being sent out from the Garmin App.

"ClubData":{"ClubHeadSpeed" "ClubAnglePath" "ClubAngleFace"}
"BallData":{"TotalSpin" "LaunchAngle" "SpinAxis" "LaunchDirection""BallSpeed"}

These are the only fields out of the Garmin application. Even though the Garmin screen is showing more data than this, it is not sending it to the PC running GSPro and the Connect App. Can't pass something to GsPro that is being given to you....

**Comment by alleexx** [comment]
Yes, Angle of Attach is not provided in the e6 interface which is being used in this connector. You will only get AoA if using the direct bluetooth connector from matth - https://github.com/mholow/gsp-r10-adapter .

**Comment by travislang** [comment]
Thanks everyone for explaining how this isn't possible in this current form.  Closing
